### ISSUE TITLE
Create find page

### ISSUE THREAD

**Issue by nickmask** [in-depth/indepth-demo#1]
Initial page has options for:
- [ ]  Find by photo
- [ ]  Find by ID - Issue #7 
- [ ]  Find by nearby - Issue #8 

Collection item page has option for:
- [ ]  General info - Issue #10 
- [ ]  Other ways to view (VR, 3D, Deep zoom) - Issue #11 & #12 
- [ ]  Link to map location
- [ ]  20 items in the database - Issue #9 

![20160925_185839](https://cloud.githubusercontent.com/assets/15827526/18813396/36581a82-8355-11e6-898c-4842f92fb358.jpg)
