### ISSUE TITLE
Demo Features - The todo list

### ISSUE THREAD

**Issue by ro-savage** [in-depth/indepth-demo#48]
I would like to get a bunch of 'demo features' made available. As people keep thinking we only do what we do, and dont seem to understand that we can do whatever the hell we want.

These would just be on a 'features' page where they can try out all these things.
Some will just be click and it does something. Others take to a demo page
- [x] Vibrate - #51 
- [x] Notification - #49 
- [x] Play audio, including playing with navigating away and controlling from lock screen - #53 
- [x] Full screen mode - #44 
- [x] Voice recognition -  #52 - [G]
- [x] Inline editing - #38 
- [ ] Desktop view - #41 - @gerardmrk @nickmask Lets try get this done asap. Thanks!
- [x] Camera + Take photo - #60
- [x] 3D model
- [x] Deep Zoom
- [ ] 360 Video - #62
- [ ] Offline mode - #61
- [ ] Saving data offline (Maybe save their name in local storage and then show it again) - #63
- [ ] Chatbot - #64
- [ ] Some AR thing, overlay an image on the camera. let people save the photo - #65
- [ ] Face tracking - #66
- [ ] Display something on lock screen (Not sure if this is possible)
- [ ] Eddystone beacon notification
- [ ] Eddystone 'show nearby objects'
- [ ] NFC reader
- [ ] QR Code reader in app
- [ ] Pull data from Digital NZ
- [ ] ORC from Te Papa label (Reading the letters/words and going to the correct item)
- [ ] Show whats around me (using eddystone, wifi, last object, click map location, qr code)

---

I will create issues for each and link them here. For now this is an idea of things you could think about/work on.

---
